x-enviroment-defaults: &enviroment-defaults
  DEBUG: 'False'
  DB_NAME: postgres
  DB_USER: postgres
  DB_PASSWORD: postgres
  DB_HOST: db
  DB_PORT: 5432
  CELERY_BROKER_URL: 'redis://redis:6379/'
  CELERY_RESULT_BACKEND: 'redis://redis:6379/'
  CACHES_LOCATION: 'redis://redis:6379/'
  REDIS_HOST: 'redis'
  DJANGO_SETTINGS_MODULE: 'forum.settings'

services:
  redis:
    image: redis:7.0.2
    restart: always
    container_name: redis
    ports:
      - '6379:6379'
  db:
    image: postgres:14.5
    restart: always
    container_name: db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
  web:
    build: 
      context: ./forum
    container_name: web
    ports:
      - '8000:8000'
    depends_on:
      - db
      - redis
    environment:
      <<: *enviroment-defaults
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
  nginx:
    image: nginx:1.26
    restart: always
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/static
      - ./scripts:/scripts
      - media_volume:/media
    ports:
      - '80:80'
    depends_on:
      - web
    entrypoint: sh -c "chmod +x /scripts/wait-for-it.sh && /scripts/wait-for-it.sh web:8000 -- nginx -g 'daemon off;'"
  celery-worker:
    build: 
      context: ./forum
    container_name: celery-worker
    command: celery -A forum.celery:app worker --loglevel=info
    environment:
      <<: *enviroment-defaults
    depends_on:
      - redis
      - db
  celery-beat:
    build: 
      context: ./forum
    container_name: celery-beat
    command: celery -A forum.celery:app beat --loglevel=info
    environment:
      <<: *enviroment-defaults
    depends_on:
      - redis
      - db
volumes:
  static_volume:
  media_volume: