# Generated by Django 4.1 on 2024-07-26 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_message_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='author_to',
        ),
        migrations.AddField(
            model_name='message',
            name='parent_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_messages', to='content.message'),
        ),
    ]
