# Generated by Django 4.1 on 2024-07-26 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('content', '0004_remove_message_author_to_message_parent_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='message',
            name='object_id',
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('text', 'video', 'image')}, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='contenttypes.contenttype')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='content.message')),
            ],
        ),
    ]
