# Generated by Django 4.1 on 2024-07-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_remove_message_content_type_remove_message_object_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='updated',
        ),
        migrations.AddField(
            model_name='content',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
