# Generated by Django 4.1 on 2024-08-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_subjectview'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subjectview',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='subjectview',
            name='date',
            field=models.DateField(),
        ),
    ]
