# Generated by Django 4.1 on 2024-08-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.FileField(default='photo_profiles/default.jpg', upload_to='photo_profiles'),
        ),
    ]
